version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ridejournaldata:/var/lib/mysql

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  ridejournaldata:
