version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ridejournaldata:/var/lib/mysql

  app:
    build: .
    restart: always
    environment:
      - DB_NAME=ridejournaldb
      - DB_USERNAME=root
      - DB_PASSWORD=pa55word
      - DB_HOST=db
      - DB_PORT=3306
      - DB_SSL=false
      - BASE_URL=http://localhost:3000
      - PORT=3000
      - CLIENT_URL=http://localhost:8080
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_started

volumes:
  ridejournaldata:
